export default {
  MARK_AS_READ: 'MARK_AS_READ',
  SET_TYPE_FILTER: 'SET_TYPE_FILTER',
  // FETCH_NOTIFICATIONS_SUCCESS felt like an anti-pattern
  SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  FILTERS: {
    DEFAULT: 'DEFAULT',
    URGENT: 'URGENT',
  }
}

export const NotificationTypeFilters = {
  DEFAULT: 'DEFAULT',
  URGENT: 'URGENT',
}
